/*
This file is part of OpenLogos/LogOSMaTrans.  Copyright (C) 2005 Globalware AG

OpenLogos/LogOSMaTrans has two licensing options:

The Commercial License, which allows you to provide commercial software
licenses to your customers or distribute Logos MT based applications or to use
LogOSMaTran for commercial purposes. This is for organizations who do not want
to comply with the GNU General Public License (GPL) in releasing the source
code for their applications as open source / free software.

The Open Source License allows you to offer your software under an open source
/ free software license to all who wish to use, modify, and distribute it
freely. The Open Source License allows you to use the software at no charge
under the condition that if you use OpenLogos/LogOSMaTran in an application you
redistribute, the complete source code for your application must be available
and freely redistributable under reasonable conditions. GlobalWare AG bases its
interpretation of the GPL on the Free Software Foundation's Frequently Asked
Questions.

OpenLogos is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the License conditions along with this
program. If not, write to Globalware AG, Hospitalstraﬂe 6, D-99817 Eisenach.

Linux port modifications and additions by Bernd Kiefer, Walter Kasper,
Deutsches Forschungszentrum fuer kuenstliche Intelligenz (DFKI)
Stuhlsatzenhausweg 3, D-66123 Saarbruecken
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI */

#ifndef _Included_logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
#define _Included_logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TRANSLATE_DOC
#define logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TRANSLATE_DOC 0L
#undef logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TRANSLATE_TEXT
#define logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TRANSLATE_TEXT 1L
#undef logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TERM_SEARCH_DOC
#define logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TERM_SEARCH_DOC 2L
#undef logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TERM_SEARCH_TEXT
#define logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_TERM_SEARCH_TEXT 3L
#undef logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_QRY_CONFIGURATION
#define logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI_QRY_CONFIGURATION 4L
/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    InitializeTranslationSession
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_InitializeTranslationSession
  (JNIEnv *, jobject);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    StartTranslationSession
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_StartTranslationSession
  (JNIEnv *, jobject);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    CloseTranslationSession
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_CloseTranslationSession
  (JNIEnv *, jobject);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    SetInputParameter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_SetInputParameter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    SetOperationType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_SetOperationType
  (JNIEnv *, jobject, jint);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    GetOutputValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_GetOutputValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_GetLastError
  (JNIEnv *, jobject);

/*
 * Class:     logos_0005fjava_GlobalWordsEngineAPI_GlobalWordsEngineAPI
 * Method:    GetLastErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_logos_1java_GlobalWordsEngineAPI_GlobalWordsEngineAPI_GetLastErrorString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
