/*
This file is part of OpenLogos/LogOSMaTrans.  Copyright (C) 2005 Globalware AG

OpenLogos/LogOSMaTrans has two licensing options:

The Commercial License, which allows you to provide commercial software
licenses to your customers or distribute Logos MT based applications or to use
LogOSMaTran for commercial purposes. This is for organizations who do not want
to comply with the GNU General Public License (GPL) in releasing the source
code for their applications as open source / free software.

The Open Source License allows you to offer your software under an open source
/ free software license to all who wish to use, modify, and distribute it
freely. The Open Source License allows you to use the software at no charge
under the condition that if you use OpenLogos/LogOSMaTran in an application you
redistribute, the complete source code for your application must be available
and freely redistributable under reasonable conditions. GlobalWare AG bases its
interpretation of the GPL on the Free Software Foundation's Frequently Asked
Questions.

OpenLogos is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the License conditions along with this
program. If not, write to Globalware AG, Hospitalstraﬂe 6, D-99817 Eisenach.

Linux port modifications and additions by Bernd Kiefer, Walter Kasper,
Deutsches Forschungszentrum fuer kuenstliche Intelligenz (DFKI)
Stuhlsatzenhausweg 3, D-66123 Saarbruecken
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class logos_0005fjava_GermanHalfNoun_GermanHalfNoun */

#ifndef _Included_logos_0005fjava_GermanHalfNoun_GermanHalfNoun
#define _Included_logos_0005fjava_GermanHalfNoun_GermanHalfNoun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     logos_0005fjava_GermanHalfNoun_GermanHalfNoun
 * Method:    InitializeHalfNounEnvironment
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_logos_1java_GermanHalfNoun_GermanHalfNoun_InitializeHalfNounEnvironment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     logos_0005fjava_GermanHalfNoun_GermanHalfNoun
 * Method:    FindHeadWordPosition
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_logos_1java_GermanHalfNoun_GermanHalfNoun_FindHeadWordPosition
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     logos_0005fjava_GermanHalfNoun_GermanHalfNoun
 * Method:    CloseHalfNounEnvironment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_logos_1java_GermanHalfNoun_GermanHalfNoun_CloseHalfNounEnvironment
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
